###//user authentication//
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"nava123",
    "password": "nava@146"
}

###//user Details//
GET http://localhost:3000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5hdmFrYW50aDEyNCIsImlhdCI6MTYzMDU4MDkxOX0.bZqt-QOyXCxKwckmZQjKPVIU3Yj5FZ3oLXHMSSvEaP4

###//casting vote//

PUT http://localhost:3000/voting/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5hdmFrYW50aDEyNCIsImlhdCI6MTYzMDU4MDkxOX0.bZqt-QOyXCxKwckmZQjKPVIU3Yj5FZ3oLXHMSSvEaP4

###//admin adding candidates to voting poll//

POST http://localhost:3000/pollUsers
Content-Type: application/json

{
    "name":"Kholi",
    "votes":13
}


###//admin adding candidates into database//
POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"nava123",
    "name":"Navakanth",
    "password":"nava@146",
    "gender":"Male",
    "location":"Hyderabad",
    "age":20
}

###//admin deleting candidates from database//
DELETE http://localhost:3000/deleteUser 
Content-Type: application/json

{
    "name":"Navakanth"
}

###//admin deleting candidates from voting poll//
DELETE http://localhost:3000/deletePollUser 
Content-Type: application/json

{
    "name":"Navakanth"
}

###//poll result//
GET http://localhost:3000/pollResult/?order_by=votes&order=DESC&limit=1
