###//user authentication//
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"nava123",
    "password": "nava@146"
}

###//admin checking user Details//
GET http://localhost:3000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdmExMjMiLCJpYXQiOjE2MzEwMDgwODZ9.W7a6l-Qb_SdvFkvYN9VKHCAwt6WMqIo__qVwmfHVspA

###//casting vote//

PUT http://localhost:3000/voting/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJha2VzaDEyMyIsImlhdCI6MTYzMTAwNzk1NH0.KySpYapJ36xB97qziW76qCA-axoGevw84z6hYuydpkI

###//admin adding candidates to voting poll//

POST http://localhost:3000/pollUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdmExMjMiLCJpYXQiOjE2MzEwMDgwODZ9.W7a6l-Qb_SdvFkvYN9VKHCAwt6WMqIo__qVwmfHVspA
Content-Type: application/json

{
    "name":"Sachin",
    "votes":12
}


###//admin adding candidates into database//
POST http://localhost:3000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdmExMjMiLCJpYXQiOjE2MzEwMDgwODZ9.W7a6l-Qb_SdvFkvYN9VKHCAwt6WMqIo__qVwmfHVspA
Content-Type: application/json

{
    "username":"rakesh123",
    "name":"Rakesh",
    "password":"rakesh@146",
    "gender":"Male",
    "location":"Hyderabad",
    "age":18,
    "role":"user"
}

###//admin deleting candidates from database//
DELETE http://localhost:3000/deleteUser 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdmExMjMiLCJpYXQiOjE2MzEwMDgwODZ9.W7a6l-Qb_SdvFkvYN9VKHCAwt6WMqIo__qVwmfHVspA
Content-Type: application/json

{
    "name":"Rakesh"
}

###//admin deleting candidates from voting poll//
DELETE http://localhost:3000/deletePollUser 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdmExMjMiLCJpYXQiOjE2MzEwMDgwODZ9.W7a6l-Qb_SdvFkvYN9VKHCAwt6WMqIo__qVwmfHVspA
Content-Type: application/json

{
    "name":"Navakanth"
}

###//poll result//
GET http://localhost:3000/pollResult/?order_by=votes&order=DESC&limit=1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdmExMjMiLCJpYXQiOjE2MzEwMDgwODZ9.W7a6l-Qb_SdvFkvYN9VKHCAwt6WMqIo__qVwmfHVspA
